version: 2.1

executors:
  gcc:
    docker:
    - image: teeks99/gcc-ubuntu:10
      environment: { CXX: g++-10, CC: gcc-10 }
  clang:
    docker:
    - image: teeks99/clang-ubuntu:12
      environment: { CXX: clang++-12, CC: clang-12 }

commands:
  install_packages:
    steps:
    - run: apt-get update -qq
    - run: apt-get install -y cmake ninja-build
  configure:
    parameters:
      build_type: { type: string }
    steps:
    - run: cmake -S . -B build -G Ninja
        -D CMAKE_BUILD_TYPE=<<parameters.build_type>>
  build:
    steps:
    - run: cmake --build build
  test:
    steps:
    - run:
        command: ctest --output-on-failure
        working_directory: build

jobs:
  build_latest_cpp17:
    parameters:
      docker: { type: executor }
      build_type: { type: string }
    executor: <<parameters.docker>>
    steps:
    - install_packages
    - checkout
    - configure: { build_type: <<parameters.build_type>> }
    - build
    - test

workflows:
  build_and_test:
    jobs:
    - build_latest_cpp17:
        matrix:
          parameters:
            docker: [gcc, clang]
            build_type: [Release]
